name: Sign IPA

on:
  push:
    branches:
      - main  # Runs on any push to main branch
    paths-ignore:
      - '**.md'  # Ignore markdown file changes
      - '.gitignore'
  workflow_dispatch:  # Keep manual trigger option

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Download and setup zsign
      - name: Setup zsign
        run: |
          wget https://github.com/zhlynn/zsign/releases/download/v1.1.0/zsign.zip
          unzip zsign.zip
          chmod +x zsign
          sudo mv zsign /usr/local/bin/

      # Create signed directory
      - name: Create signed directory
        run: mkdir -p signed

      # Sign the IPA
      - name: Sign IPA
        run: |
          zsign -k ./Cert/cert.p12 -p "1234" -m ./Cert/prov.mobileprovision -o ./signed/Feather-signed.ipa ./ipa/Feather.ipa
        
      # Debug directory contents
      - name: List directory contents
        run: |
          ls -la
          ls -la ./ipa || echo "ipa directory not found"
          ls -la ./signed || echo "signed directory not found"

      # Upload signed IPA as artifact
      - name: Upload Signed IPA
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392  # v4.0.0
        with:
          name: signed-ipa
          path: signed/Feather-signed.ipa
          if-no-files-found: error

      # Download artifacts if needed
      - name: Download artifacts
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427  # v4.1.0
        with:
          name: signed-ipa
          path: ./signed

      # Create release with signed IPA
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: ./signed/Feather-signed.ipa
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update plist file with new IPA URL
      - name: Update Plist File
        if: github.ref == 'refs/heads/main'
        run: |
          RELEASE_URL="${{ steps.create_release.outputs.upload_url }}"
          RELEASE_URL=${RELEASE_URL%\{*}
          sed -i "s|https://.*\.ipa|$RELEASE_URL|g" Feather.plist
          
      # Commit and push updated plist
      - name: Commit Plist Changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add Feather.plist
          git commit -m "Update plist with new IPA URL" || echo "No changes to commit"
          git push 